package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"fmt"
	"gql/author/models"

	"github.com/google/uuid"
)

// Name1 is the resolver for the name1 field.
func (r *authorResolver) Name1(ctx context.Context, obj *models.Author) (string, error) {
	return obj.Name, nil
}

// CreateAuthor is the resolver for the createAuthor field.
func (r *mutationResolver) CreateAuthor(ctx context.Context, input models.NewAuthor) (*models.Author, error) {
	// Lock for writing to prevent race conditions
	r.mutex.Lock()
	defer r.mutex.Unlock()

	// Generate a new unique ID for the author
	id := uuid.NewString()

	// Create a new author with the input data
	author := &models.Author{
		ID:    id,
		Name:  input.Name,
		Class: input.Class,
		Bio:   input.Bio,
	}

	// Store the author in our map
	r.authors[id] = author
	r.authorsList = append(r.authorsList, author)
	return author, nil
}

// Author is the resolver for the author field.
func (r *queryResolver) Author(ctx context.Context, id string) (*models.Author, error) {
	panic(fmt.Errorf("not implemented: Author - author"))
}

// Authors is the resolver for the authors field.
func (r *queryResolver) Authors(ctx context.Context) ([]*models.Author, error) {
	return r.authorsList, nil
}

// Author returns AuthorResolver implementation.
func (r *Resolver) Author() AuthorResolver { return &authorResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type authorResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
