// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Mutation type defines all available mutations in the API
type Mutation struct {
}

// Query type defines all available queries in the API
type Query struct {
}
